name: front to gitlab

on:
  push:
    branches:
      - frontend

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "이우성"
          git config user.email "sitpo96@naver.com"

      - name: Push to GitLab frontend branch
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git checkout frontend
          git pull origin frontend
          git checkout -b temp-frontend
          git filter-branch --force --prune-empty --index-filter "git rm -rf --cached --ignore-unmatch .github" HEAD
          git remote add gitlab https://oauth2:$GITLAB_TOKEN@lab.ssafy.com/s10-bigdata-recom-sub2/S10P22D204.git
          git push gitlab temp-frontend:frontend --force
          git checkout frontend
          git branch -D temp-frontend
